[project]
name = "tfidf-nmf"
version = "0.1.0"
requires-python = "==3.13.*"
dependencies = [
  "pip==25.3",
  "numpy==2.3.4",
  "pandas==2.3.3",
  "scikit-learn==1.7.2",
  "spacy==3.8.9",
  "beautifulsoup4==4.14.2",
  "lxml==6.0.2",
  "datasketch==1.7.0",
  "gensim==4.4.0",
  "joblib>=1.4.2",
]